meta_product_name: "AusHello"
meta_title: "AusHello - Find services, build your life"
meta_description: "Directory for refugees to find critical local resources in communities around Australia."
meta_image: "aushello_logo.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
