meta_product_name: "AusHello"
meta_title: "AusHello - Find services, build your life"
meta_description: "Location-based app to connect refugees to find critical local resources in communities around Australia."
meta_image: "aushellohome.png"
twitter_account: "@aushello_twitter_account"   # required for Twitter Cards
